import { expect, test } from "bun:test";
import fixtures from "../fixtures/quote-parity.json";
import { quoteBuyWithSolAmount, quoteSolCostForBuy, quoteSellForTokenAmount } from "../../src/ammsdk/bondingCurveMath";
import { quoteAmmBuyBudget, quoteAmmBuyCost, quoteAmmSell } from "../../src/ammsdk/amm_math";

// Static outputs generated by the official SDK versions recorded in the fixture.
// SDK dependencies and RPC are unnecessary when these deterministic tests run.
test("curve quotes match official SDK fixtures across initial reserves and integer boundaries", () => {
  for (const row of fixtures.curve) {
    const state = { virtualTokenReserves: BigInt(row.token), virtualQuoteReserves: BigInt(row.quote),
      realTokenReserves: BigInt(row.real), realQuoteReserves: BigInt(row.quote),
      creator: "So11111111111111111111111111111111111111112" };
    const fees = { lpFeeBps: BigInt(row.fees.lpFeeBps), protocolFeeBps: BigInt(row.fees.protocolFeeBps), creatorFeeBps: BigInt(row.fees.creatorFeeBps) };
    expect(quoteBuyWithSolAmount(state, fees, BigInt(row.budget)).tokenAmount).toBe(BigInt(row.expectedBuy));
    expect(quoteSolCostForBuy(state, fees, BigInt(row.amount)).totalSolCostLamports).toBe(BigInt(row.expectedCost));
    expect(quoteSellForTokenAmount(state, fees, BigInt(row.amount)).solOutputLamports).toBe(BigInt(row.expectedSell));
  }
});

test("AMM quotes match official SDK fixtures including virtual reserves and large integers", () => {
  for (const row of fixtures.amm) {
    const base = BigInt(row.base);
    const realQuote = BigInt(row.quote);
    const quote = realQuote + BigInt(row.virtual);
    const fees = { lpFeeBps: BigInt(row.fees.lpFeeBps), protocolFeeBps: BigInt(row.fees.protocolFeeBps), creatorFeeBps: BigInt(row.fees.creatorFeeBps) };
    expect(quoteAmmBuyBudget(BigInt(row.budget), base, quote, fees).tokenAmountOut).toBe(BigInt(row.expectedBuy));
    expect(quoteAmmBuyCost(BigInt(row.amount), base, quote, fees)).toBe(BigInt(row.expectedCost));
    expect(quoteAmmSell(BigInt(row.amount), base, quote, realQuote, fees)).toBe(BigInt(row.expectedSell));
  }
});
